# Generated by Django 5.0 on 2024-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_create_client_and_contact_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undefined')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.IntegerField(choices=[(0, 'phone'), (1, 'telegram'), (2, 'viber'), (3, 'whatsapp'), (4, 'instagram'), (5, 'facebook')]),
        ),
    ]
