# Generated by Django 5.0 on 2024-02-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_gender_alter_contact_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='value',
            new_name='contact',
        ),
    ]
