# Generated by Django 5.0 on 2024-01-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcal_type', models.CharField(max_length=128)),
                ('gcal_project_id', models.CharField(max_length=256)),
                ('gcal_private_key_id', models.CharField(max_length=1024)),
                ('gcal_private_key', models.TextField()),
                ('gcal_client_email', models.EmailField(max_length=254)),
                ('gcal_client_id', models.CharField(max_length=256)),
                ('gcal_auth_uri', models.URLField()),
                ('gcal_token_uri', models.URLField()),
                ('gcal_auth_provider_x509_cert_url', models.URLField()),
                ('gcal_client_x509_cert_url', models.URLField()),
                ('gcal_universe_domain', models.CharField(max_length=128)),
                ('gcal_scopes', models.URLField()),
                ('main_shop_name', models.CharField(blank=True, max_length=128)),
                ('main_color_scheme', models.CharField(blank=True, max_length=128)),
                ('main_begin_time', models.TimeField(blank=True)),
                ('main_end_time', models.TimeField(blank=True)),
            ],
            options={
                'db_table': 'siteconfig',
            },
        ),
    ]
