# Generated by Django 5.0 on 2024-01-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_create_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='main_begin_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='main_color_scheme',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='main_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='main_shop_name',
            field=models.CharField(max_length=128),
        ),
    ]
